# Generated by Django 5.2.3 on 2025-06-30 19:28

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipoVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Equipo de Venta',
                'verbose_name_plural': 'Equipos de Venta',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ComisionVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje_gerente_equipo', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('porcentaje_jefe_venta', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('porcentaje_team_leader', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('porcentaje_vendedor', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('equipo_venta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='comision_venta', to='sales_team_management.equipoventa')),
            ],
            options={
                'verbose_name': 'Comisión de Venta',
                'verbose_name_plural': 'Comisiones de Venta',
            },
        ),
        migrations.CreateModel(
            name='AsignacionEquipoProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('equipo_venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales_team_management.equipoventa')),
            ],
            options={
                'verbose_name': 'Asignación Equipo-Proyecto',
                'verbose_name_plural': 'Asignaciones Equipo-Proyecto',
            },
        ),
        migrations.CreateModel(
            name='GerenteEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('equipo_venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales_team_management.equipoventa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gerente_equipos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gerente de Equipo',
                'verbose_name_plural': 'Gerentes de Equipo',
                'unique_together': {('usuario', 'equipo_venta')},
            },
        ),
        migrations.CreateModel(
            name='GerenteProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gerente_proyectos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gerente de Proyecto',
                'verbose_name_plural': 'Gerentes de Proyecto',
            },
        ),
        migrations.CreateModel(
            name='JefeProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gerente_proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jefeproyectos', to='sales_team_management.gerenteproyecto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jefe_proyectos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Jefe de Proyecto',
                'verbose_name_plural': 'Jefes de Proyecto',
            },
        ),
        migrations.CreateModel(
            name='JefeVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gerente_equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jefeventas', to='sales_team_management.gerenteequipo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jefe_ventas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Jefe de Venta',
                'verbose_name_plural': 'Jefes de Venta',
            },
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('precio_desde', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('precio_hasta', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('planificacion', 'Planificación'), ('desarrollo', 'En Desarrollo'), ('construccion', 'En Construcción'), ('comercializacion', 'En Comercialización'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], default='planificacion', max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('equipos_venta', models.ManyToManyField(related_name='proyectos', through='sales_team_management.AsignacionEquipoProyecto', to='sales_team_management.equipoventa')),
                ('gerente_proyecto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proyectos', to='sales_team_management.gerenteproyecto')),
                ('jefe_proyecto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proyectos', to='sales_team_management.jefeproyecto')),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ComisionDesarrollo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje_gerente_proyecto', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('porcentaje_jefe_proyecto', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proyecto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='comision_desarrollo', to='sales_team_management.proyecto')),
            ],
            options={
                'verbose_name': 'Comisión de Desarrollo',
                'verbose_name_plural': 'Comisiones de Desarrollo',
            },
        ),
        migrations.AddField(
            model_name='asignacionequipoproyecto',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales_team_management.proyecto'),
        ),
        migrations.CreateModel(
            name='TeamLeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('jefe_venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teamleaders', to='sales_team_management.jefeventa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_leaders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Team Leader',
                'verbose_name_plural': 'Team Leaders',
            },
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('team_leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendedores', to='sales_team_management.teamleader')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendedores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vendedor',
                'verbose_name_plural': 'Vendedores',
            },
        ),
        migrations.CreateModel(
            name='Inmueble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('tipo', models.CharField(choices=[('apartamento', 'Apartamento'), ('casa', 'Casa'), ('local', 'Local Comercial'), ('oficina', 'Oficina'), ('bodega', 'Bodega'), ('parqueadero', 'Parqueadero')], max_length=20)),
                ('area_construida', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('area_terreno', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('precio_base', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('reservado', 'Reservado'), ('vendido', 'Vendido'), ('bloqueado', 'Bloqueado')], default='disponible', max_length=20)),
                ('piso', models.IntegerField(blank=True, null=True)),
                ('orientacion', models.CharField(blank=True, choices=[('norte', 'Norte'), ('sur', 'Sur'), ('este', 'Este'), ('oeste', 'Oeste'), ('noreste', 'Noreste'), ('noroeste', 'Noroeste'), ('sureste', 'Sureste'), ('suroeste', 'Suroeste')], max_length=20, null=True)),
                ('caracteristicas', models.TextField(blank=True)),
                ('disponible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inmuebles', to='sales_team_management.proyecto')),
            ],
            options={
                'verbose_name': 'Inmueble',
                'verbose_name_plural': 'Inmuebles',
                'ordering': ['proyecto', 'codigo'],
                'unique_together': {('proyecto', 'codigo')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='asignacionequipoproyecto',
            unique_together={('proyecto', 'equipo_venta')},
        ),
    ]
