# Generated by Django 5.2.3 on 2025-06-30 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_team_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipoventa',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
