# Generated by Django 5.2.3 on 2025-07-04 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_team_management', '0002_make_equipo_nombre_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacionequipoproyecto',
            name='equipo_venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales_team_management.equipoventa'),
        ),
        migrations.AlterField(
            model_name='asignacionequipoproyecto',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales_team_management.proyecto'),
        ),
        migrations.AlterField(
            model_name='comisiondesarrollo',
            name='proyecto',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='comision_desarrollo', to='sales_team_management.proyecto'),
        ),
        migrations.AlterField(
            model_name='comisionventa',
            name='equipo_venta',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='comision_venta', to='sales_team_management.equipoventa'),
        ),
        migrations.AlterField(
            model_name='gerenteequipo',
            name='equipo_venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales_team_management.equipoventa'),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inmuebles', to='sales_team_management.proyecto'),
        ),
        migrations.AlterField(
            model_name='jefeproyecto',
            name='gerente_proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jefeproyectos', to='sales_team_management.gerenteproyecto'),
        ),
        migrations.AlterField(
            model_name='jefeventa',
            name='gerente_equipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jefeventas', to='sales_team_management.gerenteequipo'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='equipos_venta',
            field=models.ManyToManyField(related_name='proyectos', through='sales_team_management.AsignacionEquipoProyecto', to='sales_team_management.equipoventa'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='gerente_proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proyectos', to='sales_team_management.gerenteproyecto'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='jefe_proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proyectos', to='sales_team_management.jefeproyecto'),
        ),
        migrations.AlterField(
            model_name='teamleader',
            name='jefe_venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teamleaders', to='sales_team_management.jefeventa'),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='team_leader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendedores', to='sales_team_management.teamleader'),
        ),
    ]
