# Generated by Django 5.2.3 on 2025-07-04 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_team_management', '0003_alter_asignacionequipoproyecto_equipo_venta_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='equipos_venta',
        ),
        migrations.RemoveField(
            model_name='comisiondesarrollo',
            name='proyecto',
        ),
        migrations.RemoveField(
            model_name='gerenteproyecto',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='gerente_proyecto',
        ),
        migrations.RemoveField(
            model_name='jefeproyecto',
            name='gerente_proyecto',
        ),
        migrations.AlterUniqueTogether(
            name='inmueble',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='inmueble',
            name='proyecto',
        ),
        migrations.RemoveField(
            model_name='jefeproyecto',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='jefe_proyecto',
        ),
        migrations.DeleteModel(
            name='AsignacionEquipoProyecto',
        ),
        migrations.DeleteModel(
            name='ComisionDesarrollo',
        ),
        migrations.DeleteModel(
            name='GerenteProyecto',
        ),
        migrations.DeleteModel(
            name='Inmueble',
        ),
        migrations.DeleteModel(
            name='JefeProyecto',
        ),
        migrations.DeleteModel(
            name='Proyecto',
        ),
    ]
