# Generated by Django 5.2.3 on 2025-07-22 22:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_team_management', '0004_remove_proyecto_equipos_venta_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupervisionDirecta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_supervision', models.CharField(choices=[('GERENTE_TO_VENDEDOR', 'Gerente supervisa Vendedor directamente'), ('GERENTE_TO_TEAMLEADER', 'Gerente supervisa Team Leader directamente'), ('JEFE_TO_VENDEDOR', 'Jefe Venta supervisa Vendedor directamente')], help_text='Tipo de relación de supervisión directa', max_length=50)),
                ('activo', models.BooleanField(default=True, help_text='Si esta supervisión directa está activa')),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_fin', models.DateTimeField(blank=True, help_text='Fecha cuando terminó esta supervisión directa', null=True)),
                ('notas', models.TextField(blank=True, help_text='Notas adicionales sobre esta supervisión directa')),
                ('equipo_venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervisiones_directas', to='sales_team_management.equipoventa')),
                ('subordinado', models.ForeignKey(help_text='Usuario que reporta directamente al supervisor', on_delete=django.db.models.deletion.CASCADE, related_name='supervisores_directos', to=settings.AUTH_USER_MODEL)),
                ('supervisor', models.ForeignKey(help_text='Usuario que actúa como supervisor directo', on_delete=django.db.models.deletion.CASCADE, related_name='subordinados_directos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Supervisión Directa',
                'verbose_name_plural': 'Supervisiones Directas',
                'ordering': ['-fecha_inicio'],
                'unique_together': {('subordinado', 'equipo_venta', 'activo')},
            },
        ),
    ]
