# Generated by Django 5.2.2 on 2025-07-30 17:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_team_management', '0005_supervisiondirecta'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipoVentaOld',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Equipo de Venta (Antiguo)',
                'verbose_name_plural': 'Equipos de Venta (Antiguos)',
                'db_table': 'sales_team_management_equipoventa_old',
            },
        ),
        migrations.CreateModel(
            name='PositionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Código único (ej: MANAGER, SUPERVISOR, AGENT)', max_length=30, unique=True, verbose_name='Código')),
                ('name', models.CharField(help_text='Nombre descriptivo (ej: Gerente, Supervisor, Vendedor)', max_length=100, verbose_name='Nombre')),
                ('applicable_unit_types', models.CharField(help_text='Tipos separados por coma (ej: SALES,PORTFOLIO) o ALL para todos', max_length=200, verbose_name='Tipos de Unidad Aplicables')),
                ('hierarchy_level', models.PositiveIntegerField(help_text='1=más alto, números mayores=más bajo', verbose_name='Nivel Jerárquico')),
                ('permissions_template', models.TextField(blank=True, help_text='JSON con permisos base para crear roles automáticamente', verbose_name='Template de Permisos')),
                ('can_supervise', models.BooleanField(default=False, help_text='Si esta posición puede tener subordinados', verbose_name='Puede Supervisar')),
                ('can_have_direct_reports', models.BooleanField(default=False, help_text='Si puede saltear niveles jerárquicos', verbose_name='Puede tener Reportes Directos')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tipo de Posición',
                'verbose_name_plural': 'Tipos de Posiciones',
                'db_table': 'sales_team_management_positiontype',
                'ordering': ['hierarchy_level', 'name'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationalUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre de la Unidad')),
                ('code', models.CharField(help_text='Código único para identificar la unidad (ej: VTA_NORTE)', max_length=20, unique=True, verbose_name='Código')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('unit_type', models.CharField(choices=[('SALES', 'Equipo de Ventas'), ('PORTFOLIO', 'Equipo de Carteras'), ('MARKETING', 'Equipo de Marketing'), ('OPERATIONS', 'Operaciones'), ('SUPPORT', 'Soporte')], max_length=20, verbose_name='Tipo de Unidad')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent_unit', models.ForeignKey(blank=True, help_text='Para estructuras anidadas (opcional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_units', to='sales_team_management.organizationalunit', verbose_name='Unidad Padre')),
            ],
            options={
                'verbose_name': 'Unidad Organizacional',
                'verbose_name_plural': 'Unidades Organizacionales',
                'db_table': 'sales_team_management_organizationalunit',
                'ordering': ['unit_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CommissionStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('structure_name', models.CharField(help_text='Nombre descriptivo para esta estructura de comisiones', max_length=100, verbose_name='Nombre de la Estructura')),
                ('commission_type', models.CharField(choices=[('SALES', 'Comisiones de Ventas'), ('PORTFOLIO', 'Comisiones de Carteras'), ('HYBRID', 'Comisiones Híbridas'), ('CUSTOM', 'Comisiones Personalizadas')], max_length=20, verbose_name='Tipo de Comisión')),
                ('position_percentages', models.JSONField(help_text='JSON con porcentajes de comisión por código de posición', verbose_name='Porcentajes por Posición')),
                ('effective_from', models.DateTimeField(verbose_name='Efectivo Desde')),
                ('effective_until', models.DateTimeField(blank=True, null=True, verbose_name='Efectivo Hasta')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organizational_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commission_structures', to='sales_team_management.organizationalunit', verbose_name='Unidad Organizacional')),
            ],
            options={
                'verbose_name': 'Estructura de Comisiones',
                'verbose_name_plural': 'Estructuras de Comisiones',
                'db_table': 'sales_team_management_commissionstructure',
                'ordering': ['-effective_from'],
            },
        ),
        migrations.CreateModel(
            name='TeamMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Inicio')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Fin')),
                ('status', models.CharField(choices=[('ACTIVE', 'Activo'), ('SUSPENDED', 'Suspendido'), ('TERMINATED', 'Terminado'), ('ON_LEAVE', 'En Licencia')], default='ACTIVE', max_length=20, verbose_name='Estado')),
                ('assignment_type', models.CharField(choices=[('PERMANENT', 'Permanente'), ('TEMPORARY', 'Temporal'), ('PROJECT', 'Por Proyecto'), ('INTERIM', 'Interino')], default='PERMANENT', max_length=20, verbose_name='Tipo de Asignación')),
                ('notes', models.TextField(blank=True, help_text='Notas adicionales sobre esta membresía', verbose_name='Notas')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organizational_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_memberships', to='sales_team_management.organizationalunit', verbose_name='Unidad Organizacional')),
                ('position_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_memberships', to='sales_team_management.positiontype', verbose_name='Tipo de Posición')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_memberships', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Membresía de Equipo',
                'verbose_name_plural': 'Membresías de Equipo',
                'db_table': 'sales_team_management_teammembership',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'organizational_unit', 'position_type', 'is_active')},
            },
        ),
        migrations.CreateModel(
            name='HierarchyRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(choices=[('NORMAL', 'Jerarquía Normal'), ('DIRECT', 'Supervisión Directa'), ('MATRIX', 'Supervisión Matricial'), ('PROJECT', 'Supervisión por Proyecto'), ('FUNCTIONAL', 'Supervisión Funcional')], default='NORMAL', max_length=20, verbose_name='Tipo de Relación')),
                ('authority_level', models.CharField(choices=[('FULL', 'Autoridad Completa'), ('FUNCTIONAL', 'Autoridad Funcional'), ('ADMINISTRATIVE', 'Autoridad Administrativa'), ('ADVISORY', 'Solo Asesoría')], default='FULL', max_length=20, verbose_name='Nivel de Autoridad')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Inicio')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Fin')),
                ('justification', models.TextField(blank=True, help_text='Razón por la cual existe esta relación jerárquica', verbose_name='Justificación')),
                ('is_primary', models.BooleanField(default=True, help_text='Si es la línea principal de reporte', verbose_name='Relación Principal')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subordinate_membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervisor_relations', to='sales_team_management.teammembership', verbose_name='Membresía Subordinado')),
                ('supervisor_membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subordinate_relations', to='sales_team_management.teammembership', verbose_name='Membresía Supervisor')),
            ],
            options={
                'verbose_name': 'Relación Jerárquica',
                'verbose_name_plural': 'Relaciones Jerárquicas',
                'db_table': 'sales_team_management_hierarchyrelation',
                'ordering': ['-created_at'],
            },
        ),
    ]
