# Generated by Django 5.2.2 on 2025-07-30 17:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_team_management', '0006_add_new_hierarchy_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name='EquipoVentaOld',
        ),
        migrations.AlterUniqueTogether(
            name='teammembership',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='positiontype',
            name='permissions_template',
        ),
        migrations.AlterField(
            model_name='commissionstructure',
            name='commission_type',
            field=models.CharField(choices=[('SALES', 'Comisiones de Venta'), ('PORTFOLIO', 'Comisiones de Cartera'), ('HYBRID', 'Comisiones Híbridas')], max_length=20),
        ),
        migrations.AlterField(
            model_name='commissionstructure',
            name='effective_from',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='commissionstructure',
            name='effective_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commissionstructure',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='commissionstructure',
            name='organizational_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales_team_management.organizationalunit'),
        ),
        migrations.AlterField(
            model_name='commissionstructure',
            name='position_percentages',
            field=models.JSONField(default=dict, help_text='Porcentajes por posición'),
        ),
        migrations.AlterField(
            model_name='commissionstructure',
            name='structure_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='hierarchyrelation',
            name='authority_level',
            field=models.CharField(choices=[('FULL', 'Autoridad Completa'), ('FUNCTIONAL', 'Autoridad Funcional'), ('ADMINISTRATIVE', 'Autoridad Administrativa')], default='FULL', max_length=20),
        ),
        migrations.AlterField(
            model_name='hierarchyrelation',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hierarchyrelation',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='hierarchyrelation',
            name='is_primary',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='hierarchyrelation',
            name='justification',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='hierarchyrelation',
            name='relation_type',
            field=models.CharField(choices=[('NORMAL', 'Jerarquía Normal'), ('DIRECT', 'Supervisión Directa'), ('MATRIX', 'Estructura Matricial'), ('PROJECT', 'Por Proyecto')], default='NORMAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='hierarchyrelation',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='hierarchyrelation',
            name='subordinate_membership',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervisor_relations', to='sales_team_management.teammembership'),
        ),
        migrations.AlterField(
            model_name='hierarchyrelation',
            name='supervisor_membership',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subordinate_relations', to='sales_team_management.teammembership'),
        ),
        migrations.AlterField(
            model_name='organizationalunit',
            name='code',
            field=models.CharField(max_length=20, unique=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='organizationalunit',
            name='parent_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sales_team_management.organizationalunit'),
        ),
        migrations.AlterField(
            model_name='positiontype',
            name='applicable_unit_types',
            field=models.CharField(max_length=200, verbose_name='Tipos de Unidad Aplicables'),
        ),
        migrations.AlterField(
            model_name='positiontype',
            name='can_have_direct_reports',
            field=models.BooleanField(default=False, verbose_name='Puede tener Reportes Directos'),
        ),
        migrations.AlterField(
            model_name='positiontype',
            name='can_supervise',
            field=models.BooleanField(default=False, verbose_name='Puede Supervisar'),
        ),
        migrations.AlterField(
            model_name='positiontype',
            name='code',
            field=models.CharField(max_length=30, unique=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='positiontype',
            name='hierarchy_level',
            field=models.PositiveIntegerField(verbose_name='Nivel Jerárquico'),
        ),
        migrations.AlterField(
            model_name='positiontype',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='teammembership',
            name='assignment_type',
            field=models.CharField(choices=[('PERMANENT', 'Permanente'), ('TEMPORARY', 'Temporal'), ('PROJECT', 'Por Proyecto')], default='PERMANENT', max_length=20),
        ),
        migrations.AlterField(
            model_name='teammembership',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teammembership',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='teammembership',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='teammembership',
            name='organizational_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales_team_management.organizationalunit'),
        ),
        migrations.AlterField(
            model_name='teammembership',
            name='position_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales_team_management.positiontype'),
        ),
        migrations.AlterField(
            model_name='teammembership',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='teammembership',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Activo'), ('SUSPENDED', 'Suspendido'), ('TERMINATED', 'Terminado')], default='ACTIVE', max_length=20),
        ),
        migrations.AlterField(
            model_name='teammembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_memberships', to=settings.AUTH_USER_MODEL),
        ),
    ]
