# Generated by Django 5.2.2 on 2025-08-01 13:57
# MIGRATION TO DROP LEGACY TABLES AFTER SUCCESSFUL DATA MIGRATION

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_team_management', '0007_add_hierarchy_models_direct'),
    ]

    operations = [
        # WARNING: This migration will permanently drop legacy tables
        # Only run this AFTER confirming that:
        # 1. Data migration is complete and verified
        # 2. All views and templates use new models
        # 3. Full backup has been created
        
        migrations.RunSQL(
            sql="DROP TABLE IF EXISTS sales_team_management_supervisiondirecta CASCADE;",
            reverse_sql="-- Cannot reverse this operation",
        ),
        
        migrations.RunSQL(
            sql="DROP TABLE IF EXISTS sales_team_management_vendedor CASCADE;",
            reverse_sql="-- Cannot reverse this operation",
        ),
        
        migrations.RunSQL(
            sql="DROP TABLE IF EXISTS sales_team_management_teamleader CASCADE;",
            reverse_sql="-- Cannot reverse this operation",
        ),
        
        migrations.RunSQL(
            sql="DROP TABLE IF EXISTS sales_team_management_jefeventa CASCADE;",
            reverse_sql="-- Cannot reverse this operation",
        ),
        
        migrations.RunSQL(
            sql="DROP TABLE IF EXISTS sales_team_management_gerenteequipo CASCADE;",
            reverse_sql="-- Cannot reverse this operation",
        ),
        
        migrations.RunSQL(
            sql="DROP TABLE IF EXISTS sales_team_management_equipoventa CASCADE;",
            reverse_sql="-- Cannot reverse this operation",
        ),
        
        # Also drop legacy commission tables if they exist
        migrations.RunSQL(
            sql="DROP TABLE IF EXISTS sales_team_management_comisionventa CASCADE;",
            reverse_sql="-- Cannot reverse this operation",
        ),
        
        migrations.RunSQL(
            sql="DROP TABLE IF EXISTS sales_team_management_comisiondesarrollo CASCADE;",
            reverse_sql="-- Cannot reverse this operation",
        ),
    ]
