# Generated by Django 5.2.2 on 2025-08-08 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_team_management', '0009_add_public_registration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supervisiondirecta',
            name='equipo_venta',
        ),
        migrations.RemoveField(
            model_name='gerenteequipo',
            name='equipo_venta',
        ),
        migrations.AlterUniqueTogether(
            name='gerenteequipo',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='gerenteequipo',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='jefeventa',
            name='gerente_equipo',
        ),
        migrations.RemoveField(
            model_name='jefeventa',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='teamleader',
            name='jefe_venta',
        ),
        migrations.AlterUniqueTogether(
            name='supervisiondirecta',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='supervisiondirecta',
            name='subordinado',
        ),
        migrations.RemoveField(
            model_name='supervisiondirecta',
            name='supervisor',
        ),
        migrations.RemoveField(
            model_name='teamleader',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='vendedor',
            name='team_leader',
        ),
        migrations.RemoveField(
            model_name='vendedor',
            name='usuario',
        ),
        migrations.AlterField(
            model_name='organizationalunit',
            name='code',
            field=models.CharField(blank=True, max_length=20, unique=True, verbose_name='Código'),
        ),
        migrations.DeleteModel(
            name='ComisionVenta',
        ),
        migrations.DeleteModel(
            name='EquipoVenta',
        ),
        migrations.DeleteModel(
            name='GerenteEquipo',
        ),
        migrations.DeleteModel(
            name='JefeVenta',
        ),
        migrations.DeleteModel(
            name='SupervisionDirecta',
        ),
        migrations.DeleteModel(
            name='TeamLeader',
        ),
        migrations.DeleteModel(
            name='Vendedor',
        ),
    ]
