# Generated by Django 5.2.2 on 2025-06-09 03:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='navigation',
            name='groups',
        ),
        migrations.AddField(
            model_name='navigation',
            name='group',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='navigation', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='role',
            name='groups',
            field=models.ManyToManyField(related_name='roles', to='auth.group'),
        ),
        migrations.DeleteModel(
            name='Group',
        ),
    ]
