# Generated by Django 5.2.2 on 2025-06-16 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_navigation_groups_navigation_group_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre de la Categoría')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Ícono de la Categoría')),
                ('color', models.CharField(choices=[('blue', 'Azul'), ('red', 'Rojo'), ('green', 'Verde'), ('purple', 'Morado'), ('yellow', 'Amarillo'), ('orange', 'Naranja'), ('pink', 'Rosa'), ('gray', 'Gris')], default='blue', max_length=20, verbose_name='Color de la Categoría')),
                ('order', models.IntegerField(default=0, verbose_name='Orden de Aparición')),
                ('is_active', models.BooleanField(default=True, verbose_name='Categoría Activa')),
                ('is_system', models.BooleanField(default=False, verbose_name='Categoría del Sistema')),
            ],
            options={
                'verbose_name': 'Categoría de Menú',
                'verbose_name_plural': 'Categorías de Menú',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='navigation',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='navigation_items', to='accounts.menucategory', verbose_name='Categoría'),
        ),
    ]
