# Generated by Django 5.2.3 on 2025-06-17 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role'),
        ('accounts', '0003_add_related_name_to_role'),
    ]

    operations = [
    ]
