# Generated by Django 5.2.3 on 2025-07-15 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_add_is_system_to_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cedula',
            field=models.CharField(blank=True, help_text='Número de cédula de identidad o documento de identificación', max_length=20, null=True, unique=True, verbose_name='Cédula de Identidad'),
        ),
        migrations.AddField(
            model_name='user',
            name='domicilio',
            field=models.CharField(blank=True, help_text='Dirección completa del domicilio', max_length=255, null=True, verbose_name='Domicilio'),
        ),
        migrations.AddField(
            model_name='user',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, help_text='Fecha de nacimiento del usuario', null=True, verbose_name='Fecha de Nacimiento'),
        ),
        migrations.AddField(
            model_name='user',
            name='latitud',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Latitud de la ubicación del domicilio', max_digits=10, null=True, verbose_name='Latitud'),
        ),
        migrations.AddField(
            model_name='user',
            name='longitud',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Longitud de la ubicación del domicilio', max_digits=11, null=True, verbose_name='Longitud'),
        ),
    ]
