# Generated by Django 5.2.3 on 2025-07-21 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_cedula_user_domicilio_user_fecha_nacimiento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telefono',
            field=models.CharField(blank=True, help_text='Número de teléfono de contacto', max_length=20, null=True, verbose_name='Teléfono'),
        ),
    ]
