# Generated by Django 5.2.2 on 2025-07-23 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='latitud',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='Latitud de la ubicación del domicilio (-90 a +90)', max_digits=10, null=True, verbose_name='Latitud'),
        ),
        migrations.AlterField(
            model_name='user',
            name='longitud',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='Longitud de la ubicación del domicilio (-180 a +180)', max_digits=10, null=True, verbose_name='Longitud'),
        ),
    ]
