# Generated by Django 5.2.2 on 2025-08-04 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_user_latitud_alter_user_longitud'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='foto_perfil',
            field=models.ImageField(blank=True, help_text='Foto de perfil del usuario (opcional)', null=True, upload_to='usuarios/fotos_perfil/', verbose_name='Foto de Perfil'),
        ),
    ]
