version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: crm_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - ./docker/certbot/conf:/etc/letsencrypt
      - ./docker/certbot/www:/var/www/certbot
      - ./static:/var/www/static
      - ./media:/var/www/media
    depends_on:
      - certbot
    restart: unless-stopped
    networks:
      - crm_network

  certbot:
    image: certbot/certbot
    container_name: crm_certbot
    volumes:
      - ./docker/certbot/conf:/etc/letsencrypt
      - ./docker/certbot/www:/var/www/certbot
    command: certonly --webroot --webroot-path=/var/www/certbot --email jorge@korban.duckdns.org --agree-tos --no-eff-email --keep-until-expiring --expand -d korban.duckdns.org
    restart: "no"
    networks:
      - crm_network

  certbot-renew:
    image: certbot/certbot
    container_name: crm_certbot_renew
    volumes:
      - ./docker/certbot/conf:/etc/letsencrypt
      - ./docker/certbot/www:/var/www/certbot
    command: renew --webroot --webroot-path=/var/www/certbot
    restart: "no"
    profiles:
      - renew
    networks:
      - crm_network

networks:
  crm_network:
    driver: bridge

volumes:
  certbot_conf:
  certbot_www: