# Generated by Django 5.2.3 on 2025-07-17 14:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_business', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_destino', models.CharField(help_text='Número de destino para pruebas', max_length=20)),
                ('template_name', models.CharField(default='hello_world', help_text='Nombre del template a usar', max_length=100)),
                ('language_code', models.CharField(default='en_US', help_text='Código de idioma', max_length=10)),
                ('mensaje_personalizado', models.TextField(blank=True, help_text='Mensaje personalizado (opcional)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(help_text='Usuario que creó la prueba', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mensaje de Prueba',
                'verbose_name_plural': 'Mensajes de Prueba',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebhookDebugMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('incoming', 'Entrante'), ('outgoing', 'Saliente'), ('webhook_event', 'Evento Webhook'), ('test_message', 'Mensaje de Prueba')], help_text='Tipo de mensaje', max_length=20)),
                ('numero_telefono', models.CharField(help_text='Número de teléfono involucrado', max_length=20)),
                ('contenido', models.TextField(help_text='Contenido del mensaje')),
                ('raw_data', models.JSONField(help_text='Datos raw del webhook o API')),
                ('respuesta_api', models.JSONField(blank=True, help_text='Respuesta de la API de WhatsApp', null=True)),
                ('estado', models.CharField(default='received', help_text='Estado del mensaje', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('config_utilizada', models.ForeignKey(blank=True, help_text='Configuración utilizada', null=True, on_delete=django.db.models.deletion.SET_NULL, to='whatsapp_business.whatsappconfig')),
            ],
            options={
                'verbose_name': 'Mensaje de Debug',
                'verbose_name_plural': 'Mensajes de Debug',
                'ordering': ['-created_at'],
            },
        ),
    ]
