# Generated by Django 5.2.3 on 2025-07-17 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_business', '0002_testmessage_webhookdebugmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappconfig',
            name='whatsapp_business_account_id',
            field=models.CharField(blank=True, help_text='ID de la cuenta de WhatsApp Business', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='whatsappconfig',
            name='app_secret',
            field=models.CharField(blank=True, help_text='Secreto de la aplicación de Facebook', max_length=100),
        ),
    ]
