# Generated by Django 5.2.2 on 2025-08-08 19:20

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0001_initial'),
        ('sales_team_management', '0010_remove_supervisiondirecta_equipo_venta_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadDistributionConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active_for_leads', models.BooleanField(default=False, help_text='¿Esta fuerza de venta puede recibir leads automáticamente?')),
                ('distribution_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Porcentaje de leads que debe recibir esta fuerza de venta', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('priority_order', models.PositiveIntegerField(default=1, help_text='Orden de prioridad para la distribución (1 = mayor prioridad)')),
                ('max_leads_per_day', models.PositiveIntegerField(blank=True, help_text='Límite máximo de leads por día (opcional)', null=True)),
                ('max_leads_per_week', models.PositiveIntegerField(blank=True, help_text='Límite máximo de leads por semana (opcional)', null=True)),
                ('notes', models.TextField(blank=True, help_text='Notas adicionales sobre la configuración')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(help_text='Usuario que creó la configuración', on_delete=django.db.models.deletion.CASCADE, related_name='lead_distributions_created', to=settings.AUTH_USER_MODEL)),
                ('last_modified_by', models.ForeignKey(help_text='Último usuario que modificó la configuración', on_delete=django.db.models.deletion.CASCADE, related_name='lead_distributions_modified', to=settings.AUTH_USER_MODEL)),
                ('organizational_unit', models.OneToOneField(help_text='Unidad organizacional/fuerza de venta', on_delete=django.db.models.deletion.CASCADE, related_name='lead_distribution', to='sales_team_management.organizationalunit')),
            ],
            options={
                'verbose_name': 'Configuración de Distribución de Leads',
                'verbose_name_plural': 'Configuraciones de Distribución de Leads',
                'ordering': ['priority_order', 'organizational_unit__name'],
            },
        ),
        migrations.CreateModel(
            name='LeadAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_type', models.CharField(choices=[('AUTOMATIC', 'Automática'), ('MANUAL', 'Manual'), ('REASSIGNMENT', 'Reasignación'), ('EMERGENCY', 'Emergencia')], default='AUTOMATIC', help_text='Tipo de asignación', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('ASSIGNED', 'Asignado'), ('ACCEPTED', 'Aceptado'), ('REJECTED', 'Rechazado'), ('TRANSFERRED', 'Transferido')], default='ASSIGNED', help_text='Estado de la asignación', max_length=20)),
                ('assigned_date', models.DateTimeField(auto_now_add=True, help_text='Fecha de asignación')),
                ('accepted_date', models.DateTimeField(blank=True, help_text='Fecha de aceptación', null=True)),
                ('notes', models.TextField(blank=True, help_text='Notas de la asignación')),
                ('distribution_config_snapshot', models.JSONField(help_text='Snapshot de la configuración al momento de la asignación')),
                ('is_active', models.BooleanField(default=True, help_text='¿Es la asignación activa actual?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(help_text='Usuario que realizó la asignación', on_delete=django.db.models.deletion.CASCADE, related_name='lead_assignments_made', to=settings.AUTH_USER_MODEL)),
                ('assigned_to_user', models.ForeignKey(blank=True, help_text='Usuario específico asignado (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(help_text='Lead asignado', on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='communications.lead')),
                ('organizational_unit', models.ForeignKey(help_text='Fuerza de venta asignada', on_delete=django.db.models.deletion.CASCADE, related_name='lead_assignments', to='sales_team_management.organizationalunit')),
            ],
            options={
                'verbose_name': 'Asignación de Lead',
                'verbose_name_plural': 'Asignaciones de Leads',
                'ordering': ['-assigned_date'],
                'indexes': [models.Index(fields=['lead', 'is_active'], name='communicati_lead_id_7bc37d_idx'), models.Index(fields=['organizational_unit', 'assigned_date'], name='communicati_organiz_411f9d_idx'), models.Index(fields=['assigned_to_user', 'status'], name='communicati_assigne_66224b_idx')],
            },
        ),
    ]
