# Generated by Django 5.2.2 on 2025-08-08 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0002_leaddistributionconfig_leadassignment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leaddistributionconfig',
            options={'ordering': ['organizational_unit__name'], 'verbose_name': 'Configuración de Distribución de Leads', 'verbose_name_plural': 'Configuraciones de Distribución de Leads'},
        ),
        migrations.RemoveField(
            model_name='leaddistributionconfig',
            name='priority_order',
        ),
    ]
