# Generated by Django 5.2.2 on 2025-08-09 03:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0003_remove_priority_order'),
        ('real_estate_projects', '0013_rename_m2m_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='inmueble',
            field=models.ForeignKey(blank=True, help_text='Inmueble de interés (se asigna cuando se define en el proceso)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='real_estate_projects.inmueble'),
        ),
    ]
