# Generated by Django 5.2.2 on 2025-08-09 03:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0004_alter_lead_inmueble'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadassignment',
            name='assigned_by',
            field=models.ForeignKey(blank=True, help_text='Usuario que realizó la asignación (null para asignaciones automáticas)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lead_assignments_made', to=settings.AUTH_USER_MODEL),
        ),
    ]
