# Generated by Django 5.2.2 on 2025-08-09 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0005_alter_leadassignment_assigned_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='estado',
            field=models.CharField(choices=[('nuevo', 'Nuevo'), ('asignado', 'Asignado'), ('en_proceso', 'En Proceso'), ('calificado', 'Calificado'), ('rechazado', 'Rechazado'), ('convertido', 'Convertido')], default='nuevo', help_text='Estado actual del lead', max_length=15),
        ),
    ]
