# Generated by Django 5.2.2 on 2025-08-09 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0006_lead_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='inmueble',
        ),
    ]
