# Generated by Django 5.2.2 on 2025-08-09 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0007_remove_inmueble_from_lead'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='estado',
            field=models.CharField(choices=[('prospecto', 'Prospecto'), ('cliente_activo', 'Cliente Activo'), ('cliente_inactivo', 'Cliente Inactivo'), ('perdido', 'Perdido')], default='prospecto', help_text='Estado del cliente: prospecto inicial, cliente activo (compró), etc.', max_length=20),
        ),
    ]
