# Generated by Django 5.2.2 on 2025-08-10 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0008_add_estado_to_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='archivo_local',
            field=models.FileField(blank=True, help_text='Archivo descargado y almacenado localmente', null=True, upload_to='whatsapp_media/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='mensaje',
            name='archivo_nombre',
            field=models.CharField(blank=True, help_text='Nombre original del archivo', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mensaje',
            name='archivo_tamaño',
            field=models.PositiveIntegerField(blank=True, help_text='Tamaño del archivo en bytes', null=True),
        ),
        migrations.AddField(
            model_name='mensaje',
            name='archivo_tipo_mime',
            field=models.CharField(blank=True, help_text='Tipo MIME del archivo (image/jpeg, audio/ogg, etc.)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mensaje',
            name='archivo_url',
            field=models.URLField(blank=True, help_text='URL temporal de WhatsApp para descargar el archivo', null=True),
        ),
        migrations.AddField(
            model_name='mensaje',
            name='caption',
            field=models.TextField(blank=True, help_text='Caption/descripción para imágenes y videos', null=True),
        ),
    ]
