# Generated by Django 5.2.2 on 2025-08-14 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0009_add_media_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensaje',
            name='tipo',
            field=models.CharField(choices=[('text', 'Texto'), ('image', 'Imagen'), ('audio', 'Audio'), ('video', 'Video'), ('document', 'Documento'), ('location', 'Ubicación'), ('template', 'Plantilla'), ('interactive', 'Interactivo'), ('contacts', 'Contacto')], default='text', help_text='Tipo de mensaje', max_length=20),
        ),
    ]
