# Generated by Django 5.2.3 on 2025-07-04 18:01

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales_team_management', '0004_remove_proyecto_equipos_venta_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AsignacionEquipoProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('equipo_venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales_team_management.equipoventa')),
            ],
            options={
                'verbose_name': 'Asignación Equipo-Proyecto',
                'verbose_name_plural': 'Asignaciones Equipo-Proyecto',
            },
        ),
        migrations.CreateModel(
            name='GerenteProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gerente_proyectos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gerente de Proyecto',
                'verbose_name_plural': 'Gerentes de Proyecto',
            },
        ),
        migrations.CreateModel(
            name='JefeProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gerente_proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jefeproyectos', to='real_estate_projects.gerenteproyecto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jefe_proyectos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Jefe de Proyecto',
                'verbose_name_plural': 'Jefes de Proyecto',
            },
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('tipo', models.CharField(choices=[('terrenos', 'Terrenos'), ('departamentos', 'Departamentos')], default='departamentos', max_length=20)),
                ('precio_desde', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('precio_hasta', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('planificacion', 'Planificación'), ('desarrollo', 'En Desarrollo'), ('construccion', 'En Construcción'), ('comercializacion', 'En Comercialización'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], default='planificacion', max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('equipos_venta', models.ManyToManyField(related_name='proyectos', through='real_estate_projects.AsignacionEquipoProyecto', to='sales_team_management.equipoventa')),
                ('gerente_proyecto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proyectos', to='real_estate_projects.gerenteproyecto')),
                ('jefe_proyecto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proyectos', to='real_estate_projects.jefeproyecto')),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Fase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('numero_fase', models.PositiveIntegerField()),
                ('fecha_inicio_prevista', models.DateField(blank=True, null=True)),
                ('fecha_entrega_prevista', models.DateField(blank=True, null=True)),
                ('fecha_entrega_real', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fases', to='real_estate_projects.proyecto')),
            ],
            options={
                'verbose_name': 'Fase',
                'verbose_name_plural': 'Fases',
                'ordering': ['proyecto', 'numero_fase'],
                'unique_together': {('proyecto', 'numero_fase')},
            },
        ),
        migrations.CreateModel(
            name='ComisionDesarrollo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje_gerente_proyecto', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('porcentaje_jefe_proyecto', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proyecto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='comision_desarrollo', to='real_estate_projects.proyecto')),
            ],
            options={
                'verbose_name': 'Comisión de Desarrollo',
                'verbose_name_plural': 'Comisiones de Desarrollo',
            },
        ),
        migrations.AddField(
            model_name='asignacionequipoproyecto',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='real_estate_projects.proyecto'),
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('numero_sector', models.PositiveIntegerField()),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sectores', to='real_estate_projects.fase')),
            ],
            options={
                'verbose_name': 'Sector',
                'verbose_name_plural': 'Sectores',
                'ordering': ['fase', 'numero_sector'],
                'unique_together': {('fase', 'numero_sector')},
            },
        ),
        migrations.CreateModel(
            name='Manzana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_manzana', models.PositiveIntegerField()),
                ('nombre', models.CharField(blank=True, max_length=50)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manzanas', to='real_estate_projects.sector')),
            ],
            options={
                'verbose_name': 'Manzana',
                'verbose_name_plural': 'Manzanas',
                'ordering': ['sector', 'numero_manzana'],
                'unique_together': {('sector', 'numero_manzana')},
            },
        ),
        migrations.CreateModel(
            name='Torre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('numero_torre', models.PositiveIntegerField()),
                ('numero_pisos', models.PositiveIntegerField()),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='torres', to='real_estate_projects.fase')),
            ],
            options={
                'verbose_name': 'Torre',
                'verbose_name_plural': 'Torres',
                'ordering': ['fase', 'numero_torre'],
                'unique_together': {('fase', 'numero_torre')},
            },
        ),
        migrations.CreateModel(
            name='Piso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_piso', models.PositiveIntegerField()),
                ('nombre', models.CharField(blank=True, max_length=50)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('torre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pisos', to='real_estate_projects.torre')),
            ],
            options={
                'verbose_name': 'Piso',
                'verbose_name_plural': 'Pisos',
                'ordering': ['torre', 'numero_piso'],
                'unique_together': {('torre', 'numero_piso')},
            },
        ),
        migrations.CreateModel(
            name='Inmueble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('tipo', models.CharField(choices=[('departamento', 'Departamento'), ('penthouse', 'Penthouse'), ('local', 'Local Comercial'), ('oficina', 'Oficina'), ('bodega', 'Bodega'), ('parqueadero', 'Parqueadero'), ('terreno', 'Terreno'), ('lote', 'Lote')], max_length=20)),
                ('area_construida', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('area_terreno', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('precio_base', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('reservado', 'Reservado'), ('vendido', 'Vendido'), ('bloqueado', 'Bloqueado')], default='disponible', max_length=20)),
                ('orientacion', models.CharField(blank=True, choices=[('norte', 'Norte'), ('sur', 'Sur'), ('este', 'Este'), ('oeste', 'Oeste'), ('noreste', 'Noreste'), ('noroeste', 'Noroeste'), ('sureste', 'Sureste'), ('suroeste', 'Suroeste')], max_length=20, null=True)),
                ('caracteristicas', models.TextField(blank=True)),
                ('disponible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inmuebles', to='real_estate_projects.fase')),
                ('manzana', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inmuebles', to='real_estate_projects.manzana')),
                ('piso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inmuebles', to='real_estate_projects.piso')),
            ],
            options={
                'verbose_name': 'Inmueble',
                'verbose_name_plural': 'Inmuebles',
                'ordering': ['fase', 'codigo'],
                'unique_together': {('fase', 'codigo')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='asignacionequipoproyecto',
            unique_together={('proyecto', 'equipo_venta')},
        ),
    ]
