# Generated by Django 5.2.3 on 2025-07-04 18:38

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate_projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inmueble',
            name='precio_base',
        ),
        migrations.RemoveField(
            model_name='inmueble',
            name='precio_venta',
        ),
        migrations.AddField(
            model_name='fase',
            name='disponible_comercializacion',
            field=models.BooleanField(default=False, help_text='Indica si la fase está disponible para comercialización'),
        ),
        migrations.AddField(
            model_name='fase',
            name='precio_m2',
            field=models.DecimalField(decimal_places=2, default=Decimal('1000.00'), help_text='Precio por metro cuadrado para inmuebles de esta fase', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='factor_precio',
            field=models.DecimalField(decimal_places=4, default=Decimal('1.0000'), help_text='Factor multiplicador sobre el precio base de la fase (1.0 = sin ajuste)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))]),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='precio_manual',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio manual que sobrescribe el cálculo automático', max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='comercializable',
            field=models.BooleanField(default=True, help_text='Indica si el proyecto está disponible para venta'),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='area_construida',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Área construida en metros cuadrados (para departamentos)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='area_terreno',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Área del terreno en metros cuadrados', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
