# Generated by Django manual migration for field requirement changes
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate_projects', '0003_remove_proyecto_comercializable_and_more'),
    ]

    operations = [
        # Alter jefe_proyecto to be nullable
        migrations.AlterField(
            model_name='proyecto',
            name='jefe_proyecto',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='proyectos',
                to='real_estate_projects.jefeproyecto'
            ),
        ),
        # Alter gerente_proyecto to be required (remove null=True, blank=True)
        migrations.AlterField(
            model_name='proyecto',
            name='gerente_proyecto',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='proyectos',
                to='real_estate_projects.gerenteproyecto'
            ),
        ),
    ]