# Generated by Django 5.2.3 on 2025-07-05 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate_projects', '0004_auto_20250704_1926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fase',
            name='disponible_comercializacion',
        ),
        migrations.AddField(
            model_name='inmueble',
            name='disponible_comercializacion',
            field=models.BooleanField(default=False, help_text='Indica si el inmueble está disponible para comercialización'),
        ),
    ]
