# Generated by Django 5.2.3 on 2025-07-07 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate_projects', '0006_ponderador_alter_inmueble_orientacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inmueble',
            name='orientacion',
        ),
    ]
