# Generated by Django 5.2.3 on 2025-07-07 19:19

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate_projects', '0008_remove_old_ponderadores'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ponderador',
            options={'ordering': ['proyecto', 'nombre'], 'verbose_name': 'Ponderador de Precio', 'verbose_name_plural': 'Ponderadores de Precio'},
        ),
        migrations.RemoveField(
            model_name='inmueble',
            name='area_construida',
        ),
        migrations.RemoveField(
            model_name='inmueble',
            name='area_terreno',
        ),
        migrations.AddField(
            model_name='inmueble',
            name='m2',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Área en metros cuadrados', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AddField(
            model_name='ponderador',
            name='proyecto',
            field=models.ForeignKey(default=1, help_text='Proyecto al que pertenece este ponderador', on_delete=django.db.models.deletion.CASCADE, related_name='ponderadores', to='real_estate_projects.proyecto'),
        ),
        migrations.AlterUniqueTogether(
            name='ponderador',
            unique_together={('proyecto', 'nombre')},
        ),
    ]
