# Generated by Django 5.2.3 on 2025-07-07 19:20

from django.db import migrations
from decimal import Decimal


def migrate_area_data(apps, schema_editor):
    """Populate m2 field with reasonable default values based on property type"""
    Inmueble = apps.get_model('real_estate_projects', 'Inmueble')
    
    # Since area_construida was already removed and there are 240 inmuebles with default 1.00 m2,
    # let's set reasonable default values based on property type
    for inmueble in Inmueble.objects.all():
        if inmueble.tipo == 'departamento':
            inmueble.m2 = Decimal('80.00')  # 80 m2 for apartments
        elif inmueble.tipo == 'penthouse':
            inmueble.m2 = Decimal('120.00')  # 120 m2 for penthouses
        elif inmueble.tipo == 'local':
            inmueble.m2 = Decimal('50.00')  # 50 m2 for commercial locals
        elif inmueble.tipo == 'oficina':
            inmueble.m2 = Decimal('40.00')  # 40 m2 for offices
        elif inmueble.tipo == 'bodega':
            inmueble.m2 = Decimal('100.00')  # 100 m2 for warehouses
        elif inmueble.tipo == 'parqueadero':
            inmueble.m2 = Decimal('12.00')  # 12 m2 for parking spots
        elif inmueble.tipo == 'terreno':
            inmueble.m2 = Decimal('200.00')  # 200 m2 for lots
        elif inmueble.tipo == 'lote':
            inmueble.m2 = Decimal('300.00')  # 300 m2 for larger lots
        else:
            inmueble.m2 = Decimal('50.00')  # Default fallback
        
        inmueble.save()


def reverse_migration(apps, schema_editor):
    """Reverse migration - set all m2 to 1.00"""
    Inmueble = apps.get_model('real_estate_projects', 'Inmueble')
    Inmueble.objects.update(m2=Decimal('1.00'))


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate_projects', '0009_alter_ponderador_options_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_area_data, reverse_migration),
    ]
