# Generated by Django 5.2.3 on 2025-07-07 23:35

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate_projects', '0010_migrate_area_to_m2'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ponderador',
            options={'ordering': ['proyecto', 'nivel_aplicacion', 'tipo', 'nombre'], 'verbose_name': 'Ponderador de Precio', 'verbose_name_plural': 'Ponderadores de Precio'},
        ),
        migrations.AlterUniqueTogether(
            name='ponderador',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='ponderador',
            name='activated_by',
            field=models.ForeignKey(blank=True, help_text='Usuario que activó este ponderador', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ponderadores_activados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ponderador',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Usuario que creó este ponderador', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ponderadores_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ponderador',
            name='deactivated_by',
            field=models.ForeignKey(blank=True, help_text='Usuario que desactivó este ponderador', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ponderadores_desactivados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ponderador',
            name='fase',
            field=models.ForeignKey(blank=True, help_text="Fase específica (solo si nivel_aplicacion es 'fase')", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ponderadores', to='real_estate_projects.fase'),
        ),
        migrations.AddField(
            model_name='ponderador',
            name='fecha_activacion',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora desde cuando está activo el ponderador', null=True),
        ),
        migrations.AddField(
            model_name='ponderador',
            name='fecha_desactivacion',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora hasta cuando está activo (opcional para permanentes)', null=True),
        ),
        migrations.AddField(
            model_name='ponderador',
            name='justificacion',
            field=models.TextField(blank=True, help_text='Razón o justificación para este ponderador/cambio'),
        ),
        migrations.AddField(
            model_name='ponderador',
            name='monto_fijo',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monto fijo a agregar/quitar (alternativo al porcentaje)', max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AddField(
            model_name='ponderador',
            name='nivel_aplicacion',
            field=models.CharField(choices=[('proyecto', 'Todo el Proyecto'), ('fase', 'Solo la Fase'), ('inmueble', 'Inmuebles Específicos')], default='proyecto', help_text='Nivel donde se aplica este ponderador', max_length=20),
        ),
        migrations.AddField(
            model_name='ponderador',
            name='ponderador_padre',
            field=models.ForeignKey(blank=True, help_text='Ponderador anterior del cual deriva esta versión', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versiones_hijo', to='real_estate_projects.ponderador'),
        ),
        migrations.AddField(
            model_name='ponderador',
            name='tipo',
            field=models.CharField(choices=[('valorizacion', 'Valorización'), ('descuento', 'Descuento'), ('promocion', 'Promoción Temporal'), ('ubicacion', 'Por Ubicación'), ('infraestructura', 'Infraestructura'), ('comercial', 'Estrategia Comercial')], default='valorizacion', help_text='Tipo de ponderador para mejor organización', max_length=20),
        ),
        migrations.AddField(
            model_name='ponderador',
            name='version',
            field=models.PositiveIntegerField(default=1, help_text='Versión del ponderador para historial'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='precio_base_m2',
            field=models.DecimalField(decimal_places=2, default=Decimal('1000.00'), help_text='Precio base por metro cuadrado del proyecto (se hereda a las fases)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='m2',
            field=models.DecimalField(decimal_places=2, help_text='Área en metros cuadrados', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='ponderador',
            name='activo',
            field=models.BooleanField(default=True, help_text='Estado actual del ponderador'),
        ),
        migrations.AlterField(
            model_name='ponderador',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Descripción detallada del ponderador'),
        ),
        migrations.AlterField(
            model_name='ponderador',
            name='nombre',
            field=models.CharField(help_text="Nombre descriptivo del ponderador (ej: 'Nuevo puente', 'Descuento lanzamiento')", max_length=100),
        ),
        migrations.AlterField(
            model_name='ponderador',
            name='porcentaje',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Porcentaje de ajuste (ej: 15.00 = +15%, -5.00 = -5%)', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('-100.00')), django.core.validators.MaxValueValidator(Decimal('500.00'))]),
        ),
        migrations.AlterField(
            model_name='ponderador',
            name='proyecto',
            field=models.ForeignKey(help_text='Proyecto al que pertenece este ponderador', on_delete=django.db.models.deletion.CASCADE, related_name='ponderadores', to='real_estate_projects.proyecto'),
        ),
        migrations.AddIndex(
            model_name='ponderador',
            index=models.Index(fields=['proyecto', 'activo'], name='real_estate_proyect_e7de2e_idx'),
        ),
        migrations.AddIndex(
            model_name='ponderador',
            index=models.Index(fields=['fase', 'activo'], name='real_estate_fase_id_3c781e_idx'),
        ),
        migrations.AddIndex(
            model_name='ponderador',
            index=models.Index(fields=['fecha_activacion', 'fecha_desactivacion'], name='real_estate_fecha_a_f2ad0d_idx'),
        ),
    ]
